[project]
name = "cache-workshop-oct-2025"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "django-seed>=0.3.1",
    "django>=5.2.7",
    "psycopg2>=2.9.11",
]
